# Generated by Django 4.0.5 on 2022-06-16 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='취미 이름')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hobby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.hobby', verbose_name='취미'),
        ),
    ]
